# Generated by Django 5.2 on 2025-05-09 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['primer_apellido', 'segundo_apellido', 'primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Tipo de contacto',
                'verbose_name_plural': 'Tipos de contacto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoVinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Tipo de vinculación',
                'verbose_name_plural': 'Tipos de vinculación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('dependencia_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_dependencias', to='directorio.dependencia')),
                ('tipo_dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='directorio.tipodependencia')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='directorio.sede')),
            ],
            options={
                'ordering': ['sede__nombre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ContactoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='directorio.persona')),
                ('tipo_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.tipocontacto')),
            ],
            options={
                'ordering': ['tipo_contacto__nombre', 'valor'],
            },
        ),
        migrations.CreateModel(
            name='ContactoDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='directorio.dependencia')),
                ('tipo_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.tipocontacto')),
            ],
            options={
                'ordering': ['tipo_contacto__nombre', 'valor'],
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.tipodocumento'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.IntegerField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('edificio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='directorio.edificio')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.AddField(
            model_name='dependencia',
            name='ubicacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dependencia', to='directorio.ubicacion'),
        ),
        migrations.CreateModel(
            name='Vinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado_laboral', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.cargo')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.dependencia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.persona')),
                ('tipo_vinculacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.tipovinculacion')),
            ],
            options={
                'ordering': ['-fecha_inicio', 'persona__primer_apellido'],
            },
        ),
    ]
