# Generated by Django 5.2 on 2025-05-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='piso_ubicacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
