# Generated by Django 5.2 on 2025-05-26 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_alter_dependencia_piso_ubicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactodependencia',
            old_name='created',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='contactodependencia',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='contactopersona',
            old_name='created',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='contactopersona',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='created',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='dependencia',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='espacio',
            old_name='created',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='espacio',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='created',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='sede',
            old_name='created',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='sede',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='ubicacion',
            old_name='created',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='ubicacion',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='vinculacion',
            old_name='created',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='vinculacion',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.RemoveField(
            model_name='contactodependencia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='contactopersona',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='vinculacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='contactodependencia',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactodependencia',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactopersona',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactopersona',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='espacio',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='espacio',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='persona',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='persona',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sede',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sede',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
