# Generated by Django 5.2 on 2025-05-09 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0003_alter_cargo_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='directorio.ubicacion'),
        ),
    ]
