# Generated by Django 5.2 on 2025-05-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0004_alter_dependencia_ubicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinculacion',
            options={'ordering': ['-fecha_inicio', 'persona__primer_apellido'], 'verbose_name': 'Vinculacion', 'verbose_name_plural': 'Vinculaciones'},
        ),
    ]
