# Generated by Django 5.2 on 2025-05-09 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0005_alter_vinculacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactodependencia',
            name='tipo_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directorio.tipocontacto'),
        ),
        migrations.AlterField(
            model_name='contactopersona',
            name='tipo_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directorio.tipocontacto'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias', to='directorio.ubicacion'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edificios', to='directorio.sede'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directorio.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='edificio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ubicacion', to='directorio.edificio'),
        ),
    ]
